services:
  # ALS Model Service
  als-service:
    build: .
    container_name: mlops-recsys-als
    ports:
      - "8001:8000"
    environment:
      - DEFAULT_MODEL=als_model
      - API_TITLE=MLOps RecSys API (ALS)
      - API_VERSION=1.0-als
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - recsys-network

  # LightFM Model Service
  lightfm-service:
    build: .
    container_name: mlops-recsys-lightfm
    ports:
      - "8002:8000"
    environment:
      - DEFAULT_MODEL=lightfm_model
      - API_TITLE=MLOps RecSys API (LightFM)
      - API_VERSION=1.0-lightfm
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - recsys-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: mlops-recsys-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - recsys-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: mlops-recsys-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - recsys-network

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: mlops-recsys-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - recsys-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  recsys-network:
    driver: bridge
